cmake_minimum_required(VERSION 3.13)
include($ENV{PICO_SDK_PATH}/pico_sdk_init.cmake)
project(bench_sha256_64k C CXX ASM)
set(CMAKE_C_STANDARD 11)
pico_sdk_init()
add_executable(bench_sha256_64k main.c)
target_compile_options(bench_sha256_64k PRIVATE -O3 -flto)
target_link_options(bench_sha256_64k PRIVATE -flto)
target_link_libraries(bench_sha256_64k pico_stdlib hardware_clocks hardware_resets)
pico_enable_stdio_uart(bench_sha256_64k 1)
pico_enable_stdio_usb(bench_sha256_64k 0)
pico_add_extra_outputs(bench_sha256_64k)
